### ISSUE TITLE
[Feature] Option to make audible beeps/sounds for log messages that match some criteria, such as errors.

### ISSUE THREAD

**Issue by colgreen** [zarunbal/LogExpert#155]
Sometime it may be useful ro hear an audible beep when errors and warnings are logged, so that we are immediately aware of problems rather than having to look. This means we can know a problem has occured as it happens, e.g. "click here and I geta beep, click there and I can two beeps", etc

Note sure what options are in .NET. There is a Console.Beep() method, but I guess that won't work if there's no console? Or may not an appropriate appraoch generally (not sure).

It woudl also be godo to have different sounds for e.g. errors and warnings, say a longer high frequency beep, and a shorter lower frequency beep. I personally would prefer to avoid WAVs and just keep it simple. If we allow sample files (e.g. WAV files) then performance might be an issue.

It may also be sensible to do set a 'produce beep' flag, and have another thread poll the flag and produce the beep, otherwise the loggign thread have low performance if many error log lines are produced in a short span of time.

**Comment by Hirogen** [comment]
What is the specific use case in your case?

Do you use Logexpert as tailing tool that runs for hours and hours and you need to have a visual / audible queue to get notified if an search expression has been met?

**Comment by colgreen** [comment]
Hi, thanks for the suggestions. Where I work LogExpert is used by most of the developers and testers I think, both of these groups of people use log expert in tail mode for long periods when developing and testing. The colour highliting is useful, but you still need to look at the window, and it might not always be visible (e.g. hidden behind another window, or on a screen you aren't looking at).

What would be nice I think, is if there was an audible beep when an ERROR occured, that would immediately bring the error to your attention, instead of discovering it seconds or minutes later. I.e. you are made aware of the error as it is happening.

We have a problem in our company that errors in log files are not being picked up on during the development and testing cycles, and we are trying to change that culture. I thought this would be one way of helping. Obviously you wouldn't want an office full of beeping laptops! but the option is there to use this with headphones when in the office.

If you think the idea is sound, I might be able to pick up the develoment and issue a pull request; if so then any pointers you can provide to get me starter would be gratefully received.

**Comment by Hirogen** [comment]
> Hi, thanks for the suggestions. Where I work LogExpert is used by most of the developers and testers I think, both of these groups of people use log expert in tail mode for long periods when developing and testing. The colour highliting is useful, but you still need to look at the window, and it might not always be visible (e.g. hidden behind another window, or on a screen you aren't looking at).
> 
> What would be nice I think, is if there was an audible beep when an ERROR occured, that would immediately bring the error to your attention, instead of discovering it seconds or minutes later. I.e. you are made aware of the error as it is happening.
> 
> We have a problem in our company that errors in log files are not being picked up on during the development and testing cycles, and we are trying to change that culture. I thought this would be one way of helping. Obviously you wouldn't want an office full of beeping laptops! but the option is there to use this with headphones when in the office.
> 
> If you think the idea is sound, I might be able to pick up the develoment and issue a pull request; if so then any pointers you can provide to get me starter would be gratefully received.

There are better tools for this kind of use case, where you have thousands of hours of logfiles that need automated analyzing and reporting.

Even though, it sounds like it, Logexpert is not a log-mangement and automated analyzing / reporting tool like (syslog-ng, splunk or graylog).

You should look into those kind of solutions, splunk and graylog should cover exactly your use case.

Logexpert is more of a manual Log analysis tool, where just load a logfile up and search through it.

There is no reporting-tool-chain or anything like it implemented (splunk, graylog have those)


If you really really dont like other solutions, you could do following (one of my colleagues did this
As posted before, you could use the Highlighter:

Create a new Highlighter
add a Regex that fits your search parameters
check the "set bookmark" checkbox
set a plugin => a small program that sends an email to one of your devs, or that does a beep, could be console program, that is started

Since you set the bookmark, it should be easily found in the logfile.
And the Plugin is started, whenever the Highlighter Marks a line

Also a little tip, logexpert gets a little bit in trouble in tailing mode when the files get to a size of 8-12 Gigabytes :D.
