### ISSUE TITLE
Outdated Chocolatey Gallery package (v1.4.4566.2)

### ISSUE THREAD

**Issue by rcmadruga** [zarunbal/LogExpert#19]
There is an outdated (v1.4.4566.2) and not maintained package for LogExpert at ChocolateyGallery:

[https://chocolatey.org/packages/logexpert](https://chocolatey.org/packages/logexpert)

As this repo is the new home for the project, it make sense to update the choco package as well. Even better if it could be done automatically from AppVeyor.

**Comment by zarunbal** [comment]
Thanks for the notice. I'll try to contact the current maintainer or check how to "take over" the package.

**Comment by zarunbal** [comment]
short update, I'm in contact and hope that this is soon finished

**Comment by zarunbal** [comment]
I'm now maintaner of this chocolatey package. I hope to update this package around this week.

**Comment by amynbe** [comment]
Hi Zarunbal, 

If it can be of any help, see below a chocolatey package I've generated for version 1.6.7. It's an internalised version, meaning it contains the logexpert zip package and doesn't need an internet connection to function.
Rename the file to .nupkg (I had to rename to .zip as github didn't accept the .nupkg extension).
You can install it as follows: `choco install logexpert -source logexpert.1.6.7.nupkg`

I obtained the package by following these steps: https://chocolatey.org/docs/how-to-recompile-packages

As rcmadruga said, it would be nice if you could generate the package as part of your build process to make things smoother in the future. It's been a few months now since the package is outdated on chocolatey.org (even broken).

[logexpert.1.6.7.zip](https://github.com/zarunbal/LogExpert/files/1799665/logexpert.1.6.7.zip)

**Comment by zarunbal** [comment]
thanks for your effort, I got the package creation automated by the build process. I submitted the new Version (1.6.10) to chocolatey and its waiting for a review.

**Comment by zarunbal** [comment]
Package got approved. If there is still a problem with the package feel free to leave a comment.

**Comment by spacemanspiff2007** [comment]
Thank you for providing via choco!
