### ISSUE TITLE
Plugins folder ignored

### ISSUE THREAD

**Issue by vanowm** [zarunbal/LogExpert#206]
It seems v1.8.7 ignore folder `plugins`, so when `dll` files moved into root folder, than the these plugins load on startup.
For example the default columnizer selection:
![image](https://user-images.githubusercontent.com/511517/142704959-4c962518-27dc-4dde-a691-a26e9b8eaa94.png)
There is no regex, json columnizer.

Or Am I doing something wrong here?

Windows 10 pro x64 build 19043.1320

**Comment by Hirogen** [comment]
Your "plugins" folder should look like this
![image](https://user-images.githubusercontent.com/8225398/142885001-8789c0d0-0aa8-41a7-928a-8657b3b1b3af.png)

this will result in a window like this:
![image](https://user-images.githubusercontent.com/8225398/142885104-902d1591-b2b1-4e72-b14f-34814cb1f0d3.png)

Could you pls check again, if you have all the dlls in the correct folder.

Also pls check if this happens if you start Logexpert with elevated rights (as admin)

**Comment by vanowm** [comment]
Found what's caused it:
I extracted downloaded .zip file with Windows Explorer. The problem with this method is that Windows marks all files downloaded from the internet as "unsafe":
![image](https://user-images.githubusercontent.com/511517/143327718-dec0199b-3b88-410e-8e1b-cd2f56d21eca.png)
Which prevented LE to load plugins until they all were "unblocked".

A better solution is to use 7zip or WinRAR to extract .zip files, they don't mark files as "unsafe"

**Comment by Hirogen** [comment]
thank you for informing us about your solution!
